jei
Project-RT/RandomTweaker-WiKi pull request #1
Opened 2023-10-03 14:56 UTC by ukmojb

2023-10-03 16:13 UTC, XHL315 commented
可以把类型定义写成 zs 形式

2023-10-03 16:14 UTC, ukmojb commented
> 可以把类型定义写成 zs 形式

xxx as string
类似于这样?

2023-10-03 16:18 UTC, XHL315 commented
> > 可以把类型定义写成 zs 形式
> 
> xxx as string 类似于这样?

yep

2023-10-03 17:23 UTC, XHL315 requested changes

2023-10-03 17:23 UTC, XHL315 commented on content/mod-expansion/jei/IJeiPanel.md
> +| setIcon(IItemStack icon)| IJeiPanel | 设置界面的显示 |
界面的物品图标

2023-10-03 17:23 UTC, XHL315 commented on content/mod-expansion/jei/IJeiPanel.md
> +| addRecipeCatalyst(IItemStack stack)| IJeiPanel | 增加配方的元素 |
我记得这个是按 R 或者按 U 键，JEI 能显示合成或者作用的物品

2023-10-03 17:23 UTC, XHL315 commented on content/mod-expansion/jei/IJeiPanel.md
> +| setRecipeCatalysts(IItemStack[] stacks)| IJeiPanel | 设置配方的元素 |
同上

2023-10-03 17:23 UTC, XHL315 commented on content/mod-expansion/jei/IJeiUtils.md
> +| createBackground(int u, int v, int width, int height, String resourceName)| IJeiBackground | 创建背景(贴图通过resourceName路径指定) |
可以说明具体路径

2023-10-03 17:23 UTC, XHL315 commented on content/mod-expansion/jei/IJeiUtils.md
> +| createArrowElement(int x, int y, int direction)| IJeiElements | 创建箭头元素，direction 参数为四个箭头, 可填 0, 1, 2, 3 |
说明一下 1, 2, 3, 4 具体是什么方向

2023-10-03 17:23 UTC, XHL315 commented on content/mod-expansion/jei/IJeiUtils.md
> +| createJeiManaBarElement(int x, int y, int mana, @Optional int mode)| IJeiElements | 创建魔力条元素，mana 为植物魔法魔力值，mode为1时填显示的魔力上限会缩小并显示缩小的倍数，不为1时上限为魔力池上限 |
我记得旧 Wiki 有说明缩小的算法

2023-10-03 17:23 UTC, XHL315 commented on content/mod-expansion/jei/README.md
> +以下为加载了JEI `Mod` 才提供的功能
Wiki 的风格是```以下为加载了`JEI`才提供的功能```

2023-10-03 17:23 UTC, XHL315 commented on content/mod-expansion/jei/IJeiUtils.md
> +| createItemSlot(String slotName, x as int, y as int, isInput as bool, hasBase as bool(此参数可不写默认为true))| IJeiSlotItem | slotName为指定槽位的id，x与y控制槽位的方位，width槽位宽度，height槽位长度，isInput 为是否是输入流体, hasBase 为是否渲染
复制粘贴忘记改了

2023-10-04 05:24 UTC, ukmojb commented on content/mod-expansion/jei/IJeiUtils.md
> +| createJeiManaBarElement(int x, int y, int mana, @Optional int mode)| IJeiElements | 创建魔力条元素，mana 为植物魔法魔力值，mode为1时填显示的魔力上限会缩小并显示缩小的倍数，不为1时上限为魔力池上限 |
> 我记得旧 Wiki 有说明缩小的算法

这个没有

2023-10-04 05:25 UTC, ukmojb commented
创建植魔花到底该写在cot还是botania?

2023-10-04 05:57 UTC, ikexing-cn commented
> 创建植魔花到底该写在cot还是botania?

cot 声明必备模组botania
然后botaia章节引用过去 ，感觉这样比较好

2023-10-04 06:11 UTC, ukmojb commented
那个点不知道该怎么写

2023-10-08 12:32 UTC, ikexing-cn commented
看起来没什么问题，哪个点不知道怎么写

> 那个点不知道该怎么写

2023-10-14 01:54 UTC, merged

2023-10-14 01:55 UTC, ikexing-cn commented
Nice work, Thanks!